"""add_gwpreference_table

Revision ID: 1dc932b095c9
Revises: c1b5d4204be5
Create Date: 2026-03-04 06:35:07.372926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dc932b095c9'
down_revision: Union[str, Sequence[str], None] = 'c1b5d4204be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gwpreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gas_name_zh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gas_name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('formula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gwp_value', sa.Float(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_qualitative', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gwpreference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gwpreference_formula'), ['formula'], unique=False)
        batch_op.create_index(batch_op.f('ix_gwpreference_gas_name_en'), ['gas_name_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_gwpreference_gas_name_zh'), ['gas_name_zh'], unique=False)

    op.drop_table('_alembic_tmp_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gwpreference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gwpreference_gas_name_zh'))
        batch_op.drop_index(batch_op.f('ix_gwpreference_gas_name_en'))
        batch_op.drop_index(batch_op.f('ix_gwpreference_formula'))

    op.drop_table('gwpreference')
    # ### end Alembic commands ###
