"""Add contact info and alter account type

Revision ID: c1b5d4204be5
Revises: 
Create Date: 2025-10-19 18:54:42.358282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c1b5d4204be5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('account',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)

    with op.batch_alter_table('companyinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('URL', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('gwp_list', schema=None) as batch_op:
        batch_op.alter_column('product_code',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_column('Field5')

    with op.batch_alter_table('utility', schema=None) as batch_op:
        batch_op.alter_column('utility_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('utility_unit',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_utility_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utility_id'))
        batch_op.alter_column('utility_unit',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('utility_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('gwp_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Field5', sa.INTEGER(), nullable=False))
        batch_op.alter_column('product_code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('companyinfo', schema=None) as batch_op:
        batch_op.drop_column('URL')
        batch_op.drop_column('email')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('telephone')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('account',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
