"""Update Account, CompanyInfo;Add Year, Boundary, EmissionSource, ActivityData

Revision ID: e32b8d3f9a65
Revises: a3f8e2d91c04
Create Date: 2026-03-23 22:08:32.524275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e32b8d3f9a65'
down_revision: Union[str, Sequence[str], None] = 'a3f8e2d91c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('year',
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('year_id'),
    sa.UniqueConstraint('year', 'account_id')
    )
    op.create_table('boundary',
    sa.Column('boundary_id', sa.Integer(), nullable=False),
    sa.Column('boundary_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['year.year_id'], ),
    sa.PrimaryKeyConstraint('boundary_id')
    )
    with op.batch_alter_table('boundary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boundary_boundary_name'), ['boundary_name'], unique=False)

    op.create_table('emission_source',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emission_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('boundary_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['boundary_id'], ['boundary.boundary_id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['year.year_id'], ),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('account_id', 'year_id', 'source_id', name='uq_source_global'),
    sa.UniqueConstraint('boundary_id', 'source_number', name='uq_source_number_per_boundary')
    )
    with op.batch_alter_table('emission_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emission_source_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_emission_source_source_name'), ['source_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_emission_source_source_number'), ['source_number'], unique=False)

    op.create_table('activity_data',
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('year_value', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('boundary_id', sa.Integer(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['boundary_id'], ['boundary.boundary_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['emission_source.source_id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['year.year_id'], ),
    sa.PrimaryKeyConstraint('data_id'),
    sa.UniqueConstraint('account_id', 'year_id', 'source_id', name='uq_activity_global'),
    sa.UniqueConstraint('source_id'),
    sa.UniqueConstraint('source_id', name='uq_activity_data_per_source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_data')
    with op.batch_alter_table('emission_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emission_source_source_number'))
        batch_op.drop_index(batch_op.f('ix_emission_source_source_name'))
        batch_op.drop_index(batch_op.f('ix_emission_source_scope'))

    op.drop_table('emission_source')
    with op.batch_alter_table('boundary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boundary_boundary_name'))

    op.drop_table('boundary')
    op.drop_table('year')
    # ### end Alembic commands ###
